### ISSUE TITLE
Error compiling webview-sys (cc exit code: 1)

### ISSUE THREAD

**Issue by max-ym** [Boscop/web-view#54]
There already was a similar issue: https://github.com/Boscop/web-view/issues/24.
It is not related as the error message is different. Library libwebkit2gtk-4.0-dev is installed.

=====================
error: failed to run custom build command for `webview-sys v0.1.1`
process didn't exit successfully: `/home/max/Projects/Idea Projects/uitaco/target/debug/build/webview-sys-d408c386a20b93e9/build-script-build` (exit code: 101)
--- stderr
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
thread 'main' panicked at '

Internal error occurred: Command "cc" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-fno-omit-frame-pointer" "-m64" "-I" "webview" "-I" "/usr/include/webkitgtk-4.0" "-I" "/usr/include/gtk-3.0" "-I" "/usr/include/at-spi2-atk/2.0" "-I" "/usr/include/at-spi-2.0" "-I" "/usr/include/dbus-1.0" "-I" "/usr/lib/x86_64-linux-gnu/dbus-1.0/include" "-I" "/usr/include/gtk-3.0" "-I" "/usr/include/gio-unix-2.0/" "-I" "/usr/include/cairo" "-I" "/usr/include/pango-1.0" "-I" "/usr/include/harfbuzz" "-I" "/usr/include/pango-1.0" "-I" "/usr/include/atk-1.0" "-I" "/usr/include/cairo" "-I" "/usr/include/pixman-1" "-I" "/usr/include/freetype2" "-I" "/usr/include/libpng16" "-I" "/usr/include/freetype2" "-I" "/usr/include/libpng16" "-I" "/usr/include/gdk-pixbuf-2.0" "-I" "/usr/include/libpng16" "-I" "/usr/include/libsoup-2.4" "-I" "/usr/include/libxml2" "-I" "/usr/include/webkitgtk-4.0" "-I" "/usr/include/glib-2.0" "-I" "/usr/lib/x86_64-linux-gnu/glib-2.0/include" "-Wall" "-Wextra" "-std=c11" "-w" "-DDEBUG" "-DWEBVIEW_GTK" "-o" "/home/max/Projects/Idea Projects/uitaco/target/debug/build/webview-sys-26f3fd6b66fc836b/out/webview.o" "-c" "webview.c" with args "cc" did not execute successfully (status code exit code: 1).

', /home/max/.cargo/registry/src/github.com-1ecc6299db9ec823/cc-1.0.32/src/lib.rs:2367:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:70
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:58
             at src/libstd/panicking.rs:200
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:215
   4: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:478
   5: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:385
   6: std::panicking::begin_panic_fmt
             at src/libstd/panicking.rs:340
   7: cc::fail
             at /home/max/.cargo/registry/src/github.com-1ecc6299db9ec823/cc-1.0.32/src/lib.rs:2367
   8: cc::Build::compile
             at /home/max/.cargo/registry/src/github.com-1ecc6299db9ec823/cc-1.0.32/src/lib.rs:951
   9: build_script_build::main
             at ./build.rs:66
  10: std::rt::lang_start::{{closure}}
             at /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858/src/libstd/rt.rs:64
  11: std::panicking::try::do_call
             at src/libstd/rt.rs:49
             at src/libstd/panicking.rs:297
  12: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:92
  13: std::rt::lang_start_internal
             at src/libstd/panicking.rs:276
             at src/libstd/panic.rs:388
             at src/libstd/rt.rs:48
  14: std::rt::lang_start
             at /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858/src/libstd/rt.rs:64
  15: main
  16: __libc_start_main
  17: _start

**Comment by max-ym** [comment]
Furthermore, it has been compiling some time earlier. After few weeks of a break from working on a project I found this error on my way of getting it compiled.

**Comment by max-ym** [comment]
I fixed the error. For some strange reason file "/usr/include/gdk-pixbuf-2.0/gdk-pixbuf/gdk-pixbuf-animation.h" was corrupted - it contained all chaotic unreadable characters. When I replaced this file with the correct one from official repo everything worked well.
